### ISSUE TITLE
Add ability to set all bounding boxes to the same species at once

### ISSUE THREAD

**Issue by r2d2bol** [ucsd-vision/InvasivePlantSpecies#10]
A panorama will usually have only one species present.  There should be a button or some way of applying the same species label to all bounding boxes.

**Comment by archerD** [comment]
The code should work now (commit f7a629e), as #13 has been fixed, and that was the root cause of the previous issue with the implementation.

**Comment by r2d2bol** [comment]
Looks good, though it needs one more feature.  Keep track of the species of the last bounding box added, and any new bounding box should default to the species of the last bounding box added.

**Comment by archerD** [comment]
Feature added, the bounding boxes added have the species set to the species which was the last to have something changed to it.
