### ISSUE TITLE
Deleting panoramas can result in an error in the bounding box div id, causing errors.

### ISSUE THREAD

**Issue by archerD** [ucsd-vision/InvasivePlantSpecies#13]
Steps to reproduce:
 1) Add a bounding box
 2) Add a second bounding box
 3) Delete first bounding box 
 4) Add a third bounding box

This results in two bounding boxes div elements with the same id.

**Comment by archerD** [comment]
Ready for review as of commit f7a629e

**Comment by r2d2bol** [comment]
Looks good, closing
