### ISSUE TITLE
Deleting Bounding box twice can cause issues

### ISSUE THREAD

**Issue by archerD** [ucsd-vision/InvasivePlantSpecies#20]
If a bounding box is deleted, then another bounding box is added, when the second bounding box is deleted, the box will be removed from the panorama, but the area below where it was will still show the bounding box.

**Comment by r2d2bol** [comment]
It might be as simple as setting selectedBBIndex=boundingBox[i].index instead of i, see findBoundingBox function in editPanorama.html

**Comment by archerD** [comment]
should be fixed
