### ISSUE TITLE
Add a cancel button to edit panorama page

### ISSUE THREAD

**Issue by r2d2bol** [ucsd-vision/InvasivePlantSpecies#6]
There should be a cancel button on the edit panorama page which discards changes and takes the user back to the all panoramas page.

**Comment by r2d2bol** [comment]
Clicking the cancel button after making some changes (e.g., adding a bounding box ) should not give you the "are you sure you want to leave this site" prompt.  You might have to set unsavedChanges to false before redirecting to the index page.

**Comment by archerD** [comment]
I did not realize that was the desired out come, has been fixed in 999f6e7.

**Comment by archerD** [comment]
Can this be closed?
