### ISSUE TITLE
Add a map view of all panoramas

### ISSUE THREAD

**Issue by r2d2bol** [ucsd-vision/InvasivePlantSpecies#7]
We should display a map of the panoramas in the database using the google maps API.  Ideally it is something like the "Placing basic markers" example here: https://developers.google.com/maps/documentation/javascript/earthquakes .  Even better would be something like the marker clustering example here: https://developers.google.com/maps/documentation/javascript/marker-clustering

**Comment by archerD** [comment]
In progress in the GoogleMap branch.  The main functionality is there, a map with markers for each panorama and the ability to choose a panorama to edit from the map.

**Comment by r2d2bol** [comment]
Looks good, this branch has been merged to master, closing.
